# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rg4up11MtVJ8cPXvfzahEOspm7NnLvnm
"""



import numpy as np
import matplotlib.pyplot as plt
a=np.linspace(-10,0,100)
plt.plot(a,np.exp(a)*(1-2*a)/4,color="b")
b=np.linspace(0,10,100)
plt.plot(b,np.exp(-b)/4,color="b")
plt.title("P.D.F of random variable $X_1-X_2$")
plt.xlabel("$Z$")
plt.ylabel("$P_Z(z)$")
plt.show()
c=np.linspace(-10,0,100)
plt.plot(c,np.exp(c)*(3-2*c)/4,color="b")
d=np.linspace(0,10,100)
plt.plot(d,1-np.exp(-d)/4,color="b")
plt.title("C.D.F of random variable $X_1-X_2$")
plt.xlabel("$Z$")
plt.ylabel("$F_Z(z)$")
plt.show()