# -*- coding: utf-8 -*-
"""Untitled20.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SNCOjBDj8baCXIrJ9nyMAbn8qpknRDTh
"""

from scipy.stats import bernoulli
#no of times the expeiment is conducting
n=100000
count1=count2=count3=0
#caluclating simulated probability  of solving problem by atleast one of them  :
a=bernoulli.rvs(size=n,p=3/5)
b=bernoulli.rvs(size=n,p=4/5)
for i in range (n):
  if (a[i]==1):
    count1=count1+1
  if (b[i]==1):
    count2=count2+1
  if (a[i]==1 and b[i]==1 ):
    count3=count3+1


simul_prob=(count1+count2-count3)/n
theory_prob=23/25
print("simulated probability is :",simul_prob)
print("theoritical probability is: ",theory_prob)
print("absolute difference between the probabilities is :",abs(simul_prob-theory_prob))
